services:
  cs2-server:
    image: joedwards32/cs2
    container_name: cs2-server
    environment:
      # Server configuration
      - SRCDS_TOKEN=$SRCDS_TOKEN      # Game Server Token from https://steamcommunity.com/dev/managegameservers
      - STEAMAPPVALIDATE=0            # (0 - no validation, 1 - enable validation)
      - CS2_SERVERNAME=$ORGA          # (Set the visible name for your private server)
      - CS2_CHEATS=0                  # (0 - disable cheats, 1 - enable cheats)
      - CS2_PORT=27015                # (CS2 server listen port tcp_udp)
      - CS2_SERVER_HIBERNATE=0        # (Put server in a low CPU state when there are no players. 0 - hibernation disabled, 1 - hibernation enabled)
      - CS2_RCON_PORT                 # (Optional, use a simple TCP proxy to have RCON listen on an alternative port. Useful for services like AWS Fargate which do not support mixed protocol ports.)
      - CS2_LAN=0                     # (0 - LAN mode disabled, 1 - LAN Mode enabled)
      - CS2_RCONPW=$RCON_PASSWD       # (RCON password)
      - CS2_PW=$SERVER_PASSWD         # (CS2 server password)
      - CS2_MAXPLAYERS=12             # (Max players)
      - CS2_ADDITIONAL_ARGS           # (Optional additional arguments to pass into cs2)
      - CS2_CFG_URL                   # HTTP/HTTPS URL to fetch a Tar Gzip bundle of configuration files/mods
      # Game modes
      - CS2_GAMEALIAS                 # (Game type, e.g. casual, competitive, deathmatch. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMETYPE=0                # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_GAMEMODE=1                # (Used if CS2_GAMEALIAS not defined. See https://developer.valvesoftware.com/wiki/Counter-Strike_2/Dedicated_Servers)
      - CS2_MAPGROUP=mg_active        # (Map pool. Ignored if Workshop maps are defined.)
      - CS2_STARTMAP=de_inferno       # (Start map. Ignored if Workshop maps are defined.)
      # TV
      - TV_AUTORECORD=0               # Automatically records all games as CSTV demos: 0=off, 1=on.
      - TV_ENABLE=0                   # Activates CSTV on server: 0=off, 1=on.
      - TV_PORT=27020                 # Host SourceTV port
      - TV_PW=$CSTV_PASSWD                # CSTV password for clients
      - TV_RELAY_PW=$CSTV_RELAY_PASSWD    # CSTV password for relay proxies
      - TV_MAXRATE=0                  # World snapshots to broadcast per second. Affects camera tickrate.
      - TV_DELAY=0                    # CSTV broadcast delay in seconds
      # Logs
      - CS2_LOG=on                    # 'on'/'off'
      - CS2_LOG_MONEY=0               # Turns money logging on/off: (0=off, 1=on)
      - CS2_LOG_DETAIL=0              # Combat damage logging: (0=disabled, 1=enemy, 2=friendly, 3=all)
      - CS2_LOG_ITEMS=0               # Turns item logging on/off: (0=off, 1=on)
    volumes:
      - ./cs2/steam:/home/steam/cs2-dedicated     # Persistent data volume mount point inside container
    ports:
      - "27015:27015/tcp"             # TCP
      - "27015:27015/udp"             # UDP
      - "27020:27020/udp"             # UDP
    stdin_open: true
    tty: true

  propilkki2:
    build:
      context: ./propilkki2
    container_name: propilkki2
    restart: unless-stopped
    ports:
      - "4500:4500"

  teamspeak3_db:
    image: mariadb
    container_name: teamspeak3_db
    restart: unless-stopped
    volumes:
      - "./teamspeak3/db:/var/lib/mysql"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    env_file: .env

  teamspeak3:
    image: carlgo11/teamspeak
    container_name: teamspeak3
    restart: unless-stopped
    environment:
      MARIADB_HOST: $TS_MARIADB_HOST
      MARIADB_PORT: $TS_MARIADB_PORT
      MARIADB_USER: $TS_MARIADB_USER
      MARIADB_PASSWORD: $TS_MARIADB_PASSWORD
      MARIADB_DATABASE: $TS_MARIADB_DATABASE
    ports:
      - "9987:9987/udp"
      - "10011:10011"
      - "30033:30033"
    volumes:
      - "./teamspeak3/ts3server_config.ini:/teamspeak/ts3server.ini:ro"
      - "./teamspeak3/init_channels.sh:/teamspeak/init_channels.sh:ro"
      - "./teamspeak3/allowlist.txt:/teamspeak/allowlist.txt:ro"
      - "./teamspeak3/files:/teamspeak/files"
      - "./teamspeak3/logs:/teamspeak/logs"
    tmpfs: "/teamspeak:exec,uid=1000,mode=700"

  mumble:
    image: "mumblevoip/mumble-server:latest"
    container_name: mumble
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    volumes:
      - mumble:/data
    environment:
      - MUMBLE_SERVER_PASSWORD=$ORGA
      - MUMBLE_SUPERUSER_PASSWORD=$ORGA
      - MUMBLE_BANDWIDTH=72000
      - MUMBLE_REGISTER=false
      - MUMBLE_CONFIG_WELCOMETEXT=$ORGA Mumble Server
    restart: unless-stopped

volumes:
  mumble: