services:
  cs2-secondary:
    image: joedwards32/cs2
    container_name: cs2-secondary
    restart: unless-stopped
    env_file:
      - .env
      - ./env/cs2.env
    volumes:
      - ./cs2-secondary/steam:/home/steam/cs2-dedicated
    ports:
      - 27016:27015/tcp
      - 27016:27015/udp
      - 27021:27020/udp
    stdin_open: true
    tty: true
